### ISSUE TITLE
在extend/context.ts 里面引入第三方包会报错

### ISSUE THREAD

**Issue by hucsin** [eggjs/tegg#177]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

1、我在项目里面extend/context.ts里面,按照redmine文档,写了一个扩展属性
`
import { Session } from '@xx/eos'

const SESSION_HELPER = Symbol('context#sessionHelper');

export default {
    /**
     * sessionHelper 
     */
    get sessionHelper() {
        if (!this[SESSION_HELPER]) {
            this[SESSION_HELPER] = new Session(2)
        }
        return this[SESSION_HELPER];
    },

};`

2、 在项目运行的时候会报如下错误:

`2023-12-13 20:52:43,219 ERROR 41983 nodejs.TypeError: Cannot read property 'protoImplType' of undefined
    at Function.createProto (/Users/xxx/Work/docker/bytehubs-eos/node_modules/.store/@eggjs+tegg-metadata@3.28.2/node_modules/@eggjs/tegg-metadata/src/factory/EggPrototypeCreatorFactory.ts:39:57)
    at AppLoadUnit.init (/Users/xxx/Work/docker/bytehubs-eos/node_modules/.store/@eggjs+tegg-plugin@3.28.2/node_modules/@eggjs/tegg-plugin/lib/AppLoadUnit.ts:53:55)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.createLoadUnit (/Users/xxx/Work/docker/bytehubs-eos/node_modules/.store/@eggjs+tegg-metadata@3.28.2/node_modules/@eggjs/tegg-metadata/src/factory/LoadUnitFactory.ts:33:7)
    at async EggModuleLoader.loadApp (/Users/xxx/Work/docker/bytehubs-eos/node_modules/.store/@eggjs+tegg-plugin@3.28.2/node_modules/@eggjs/tegg-plugin/lib/EggModuleLoader.ts:15:22)
    at async EggModuleLoader.load (/Users/xxx/Work/docker/bytehubs-eos/node_modules/.store/@eggjs+tegg-plugin@3.28.2/node_modules/@eggjs/tegg-plugin/lib/EggModuleLoader.ts:50:5)
    at async ModuleHandler.init (/Users/xxx/Work/docker/bytehubs-eos/node_modules/.store/@eggjs+tegg-plugin@3.28.2/node_modules/@eggjs/tegg-plugin/lib/ModuleHandler.ts:31:7)
    at async App.didLoad (/Users/xxx/Work/docker/bytehubs-eos/node_modules/.store/@eggjs+tegg-plugin@3.28.2/node_modules/@eggjs/tegg-plugin/app.ts:50:5)

pid: 41983`

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

v14.19.1

### TEgg 版本号：

3.28.2

### 相关插件名称与版本号：

 "dependencies": {     "@eggjs/tegg": "^3.28.1",     "@eggjs/tegg-aop-plugin": "^3.5.2",     "@eggjs/tegg-config": "^3.2.3",     "@eggjs/tegg-controller-plugin": "^3.5.2",     "@eggjs/tegg-eventbus-plugin": "^3.5.2",     "@eggjs/tegg-plugin": "^3.5.2",     "@eggjs/tegg-schedule-plugin": "^3.5.2",     "egg": "^3.15.0",     "egg-scripts": "^2.17.0",     "egg-tracer": "^2.0.0",     "glob": "^10.3.10",     "lodash": "^4.17.21"   },

### 操作平台与版本号：

mac

**Comment by killagu** [comment]
@hucsin 麻烦提供一下最小可复现的仓库，这个错误栈看不出来原因。

**Comment by hucsin** [comment]
> @hucsin 麻烦提供一下最小可复现的仓库，这个错误栈看不出来原因。

在加载的时候有办法豁免某些目录么,把我自己的仓库豁免掉, 我发现一旦我引入我公司的私有仓库就要报这个错

**Comment by hucsin** [comment]
> @hucsin 麻烦提供一下最小可复现的仓库，这个错误栈看不出来原因。

@killagu 



我人工看了下,是截图这个地方的BackgroundTaskHelper 这个对象, 这个地方获取返回值是undefined

**Comment by hucsin** [comment]
![image](https://github.com/eggjs/tegg/assets/4591820/b24ad489-86a6-49ee-8618-1e6c3169fa74)
![image](https://github.com/eggjs/tegg/assets/4591820/83901660-d5d8-442b-b26f-ac9732bdbcaa)

补充下截图

**Comment by killagu** [comment]
https://github.com/eggjs/tegg/blob/master/core/loader/src/LoaderUtil.ts#L17 调用这个可以 exclude 目录。

BackgroundTaskHelper 是框架提供的类，https://github.com/eggjs/tegg/blob/master/core/background-task/src/BackgroundTaskHelper.ts 可能是命中了 bug。

**Comment by hucsin** [comment]
@killagu  我发现loader文件有些执行了两次, 这个是正常的么

**Comment by hucsin** [comment]
我先临时修改了,把这个关闭了
