### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by mayinrain** [eggjs/tegg#182]
### Your detail info about the Bug:

What I did
1. 执行npm run tsc，清除缓存和执行tsc操作
2. 执行npm run dev，出现以下报错
![企业微信截图_17041781754794](https://github.com/eggjs/tegg/assets/73584269/c5e600cb-29eb-439e-b35a-435ea175b578)

### Reproduction Repo

无

### Node Version

18.14.0

### TEgg Version

3.12.0

### Plugin Name and its version

tegg-eventbus-plugin 3.12.0

### Platform and its version

Windows 10

**Comment by mayinrain** [comment]
想请教下这个报错一般什么情况下会遇到，我在排查错误上没有什么头绪

**Comment by mayinrain** [comment]
2024-01-02 15:27:54,755 ERROR 21596 framework.EggPrototypeNotFound: Object eventContextFactory not found in LOAD_UNIT:tegg-app [ https://eggjs.org/zh-cn/faq/TEGG_EGG_PROTO_NOT_FOUND ]
    at EggPrototypeFactory.getPrototype (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-metadata\src\factory\EggPrototypeFactory.ts:45:48)
    at EggPrototypeBuilder.tryFindDefaultPrototype (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-metadata\src\impl\EggPrototypeBuilder.ts:67:41)       
    at EggPrototypeBuilder.findInjectObjectPrototype (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-metadata\src\impl\EggPrototypeBuilder.ts:97:19)     
    at EggPrototypeBuilder.build (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-metadata\src\impl\EggPrototypeBuilder.ts:117:26)
    at create (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-metadata\src\impl\EggPrototypeBuilder.ts:62:20)
    at Function.createProto (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-metadata\src\factory\EggPrototypeCreatorFactory.ts:48:21)
    at EventbusLoadUnitHook.postCreate (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-eventbus-plugin\lib\EventbusLoadUnitHook.ts:24:56)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.callPostCreate (C:\Users\chandlermei\Desktop\wnpmcore\node_modules\@eggjs\tegg-lifecycle\src\LifycycleUtil.ts:79:5)
    at async Promise.all (index 3)
code: TEGG_EGG_PROTO_NOT_FOUND
serialNumber: EGG_PROTO_NOT_FOUND
errorContext: ""
pid: 21596
这是完整的报错信息

**Comment by killagu** [comment]
大概率是有多个版本的 @eggjs/tegg-metadata 导致的。

**Comment by nxps** [comment]
同样的问题，我发现 cnpmcore@^3.51.0 还是依赖的 tegg 3.12.0，锁版本，使用上次能正常运行的 tegg 相关包 3.12.0，cnpmcore 3.38.2, 报错如下：
`nodejs.ERR_PACKAGE_PATH_NOT_EXPORTEDError: [egg-core] load file: /Users/xxx/test/node_modules/@eggjs/tegg-orm-plugin/app.js, error: Package subpath './src/setup_hooks' is not defined by "exports" in /Users/xxx/test/node_modules/leoric/package.json`

**Comment by killagu** [comment]
@mayinrain 如果还有问题的话可以再打开 issue。我先关了。
